ros-infrastructure/rosdoc2

- rosdoc2/verbs/build/parse_rosdoc2_yaml.py
That is, don't fall back to empty defaults for them.  This
is important in case users provide their own YAML configuration,
but have a typo in them (like 'biulders' instead of 'builders').
With the default of an empty dict, the builders would just be
skipped completely, and could lead to hard-to-debug issues.
At least with this PR it would be louder.
@wjwwood @tfoote This seems fairly harmless to me, but an opinion on whether this is the right way to go is appreciated.
> Make sure both 'settings' and 'builders' are in the YAML.

- rosdoc2/verbs/build/builder.py
- rosdoc2/verbs/build/builders/__init__.py
- rosdoc2/verbs/build/builders/doxygen_builder.py
- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/inspect_package_for_settings.py
- rosdoc2/verbs/build/parse_rosdoc2_yaml.py
Make the builders a list, where the key for each one is the
type of builder and the values is a dictionary of required
and optional keys.
This may be the most important one that we agree on, since it fundamentally changes the configuration file that users provide (and thus it will be hard to change later).  Opinions welcome here.
> Change the YAML builder configuration arguments.

- README.md
- rosdoc2/verbs/build/impl.py
- rosdoc2/verbs/open/impl.py
That way users can just run it with the path to the sources,
and it will do some reasonable things by default.
> Make most of the command-line arguments optional.

- rosdoc2/verbs/build/builders/sphinx_builder.py
- setup.cfg
This makes it consistent with the documentation hosted at
https://docs.ros.org/en/foxy
As we discussed earlier, switch to RTD theme.
> Switch to Read-the-docs theme.

- rosdoc2/verbs/build/builders/sphinx_builder.py
As we discussed elsewhere, move this back to be the index landing page for now.  We can move it all back around later on when we have a more complete landing page finished.
> Switch main.html -> index.html

- rosdoc2/verbs/build/builders/sphinx_builder.py
When you have more than 1 package in a repository, rosdoc2
will automatically generate intersphinx mappings between the
packages in the repository.  Unfortunately, there is a bug
where two commas get put into the entries, which means that
sphinx throws an "invalid syntax" warning when trying to parse
it.  Fix that here by removing the first one, and just rely
on the join() later on to add commas as appropriate.
> Fix intersphinx generation.

- rosdoc2/verbs/build/builders/sphinx_builder.py
This PR fixes a warning about the library API document not being included in the document, and also fixes the sidebar rendering (table of content shows up in the sidebar correctly).
These two issues are connected because the Sphinx html theme uses the `:toctree:` directive to create the sidebar.
References:
* Exhale, link to generated documentation API: https://exhale.readthedocs.io/en/latest/usage.html#make-your-documentation-link-to-the-generated-api
* Sphinx rtd theme, table of content options: https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#table-of-contents-options
Signed-off-by: Abrar Rahman Protyasha <abrar@openrobotics.org>
> Fix toctree warnings and render toctree in the HTML sidebar

- rosdoc2/verbs/build/builders/sphinx_builder.py
- setup.cfg
This PR introduces markdown parsing support in two separate ways.
1. If there are markdown files in the `Sphinx` project where the
`SphinxBuilder` object is run, previously those files were treated as
restructured text files. By adding the `myst-parser` to the list of
extensions and by registering the `.md` source suffix to correspond
to `markdown` files, the appropriate parser will be called for any
markdown files in the `Sphinx` project tree.
This is the less likely situation because when a default `Sphinx`
project tree is generated, no files from the existing package
repository is transferred.
2. If a project's Doxygen configuration includes any markdown files,
then `exhale` provides those files with a `file_<>.rst` and a
`program_listing_<>.rst` page, where the latter is included as a …
> Add markdown parsing support to `rosdoc2`

- rosdoc2/verbs/build/builders/sphinx_builder.py
* Provide package name in `rootFileTitle`
* So, instead of `library_api`, the root file title will read `{package_name}_api` instead.
* "C++ API" -> "Package API"
* "C++ API" rests on the assumption that `rosdoc2` was invoked on a package with C++
documentation, which may not be accurate.
Signed-off-by: Abrar Rahman Protyasha <abrar@openrobotics.org>
> Package name fixes

- rosdoc2/verbs/build/builders/sphinx_builder.py
Typo: "Doxygen" -> "Sphinx".
Signed-off-by: Abrar Rahman Protyasha <abrar@openrobotics.org>
> Fix builder name when throwing RuntimeError

- rosdoc2/verbs/build/builders/sphinx_builder.py
This patch:
- Modifies default index
- Uses Exhale generated index
- Changes Exhale configuration
Requires https://github.com/svenevs/exhale/pull/114.
> Revamp default Sphinx project

- README.md
It is not available there yet.
This will fix #35
> Remove part of README that says rosdoc2 is on pip.

- rosdoc2/verbs/build/builders/sphinx_builder.py
According to the documentation, that is the syntax that is
supported.
The breathe documentation that talks about this is here: https://github.com/michaeljones/breathe/blob/master/documentation/source/directives.rst#doxygenpage
> Use :content-only: as the doxygenpage directive.

- .flake8
- rosdoc2/verbs/build/builder.py
- test/test_flake8.py
Flake8 generates warnings for both W503 and W504 - line breaks before
and after binary operators respectively.
I came across both together when running CI for #28, and it's difficult
to satisfy both. Plus, it's documented that W503 is incompatible with
PEP 8. Reference: https://bugs.python.org/issue26763
As such, this PR chooses to ignore W503 warnings for this project.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>
> [Test] Ignore W503 warnings in Flake8

- rosdoc2/verbs/build/impl.py
- rosdoc2/verbs/build/inspect_package_for_settings.py
- rosdoc2/verbs/build/parse_rosdoc2_yaml.py
This PR allows users to pass an `override_build_type` parameter via the rosdoc2.yaml settings.
I've found this to be the easiest way to get document generation for `rclpy` like packages to work. ie, where the `build_type` in `package.xml` is `ament_cmake` but we want autodoc generation of the python modules within `rclpy/rclpy`.
> Feature: Override build_type via rosdoc2 yaml

- setup.cfg
- test/test_flake8.py
With these markers present, pytest can be used to filter for or against "linter" or "flake8", as is possible in other ROS packages.
Additionally, by moving the imports for flake8 into the test body, tests can be executed without flake8 installed (as is a common practice in system packaging).
> Add pytest markers, junit suite name

- README.md
minor fix to address https://github.com/ros-infrastructure/rosdoc2/issues/66
> update install procedure and prerequisite.

- .github/workflows/test.yml
It's a fairly trivial point, but people running ros2 (and rosdoc2) are more likely to be on ubuntu-22.04 rather than ubuntu-20.04, so update the action runner to support this. Also add python3.10 since that is now the default version.
> Use ros docker images in github runner

- README.md
- rosdoc2/main.py
When developing rosdoc2, it can be convenient to run it as a module directly rather than having to install each time, or trying to make an editable install work. This minor change should allow it.
> Allow running as module

- rosdoc2/verbs/build/build_context.py
- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/inspect_package_for_settings.py
- test/test_builder.py
This enables displaying python API in a mixed module with C++.
You can see the effects in the full_package test case. That is, run the tests. Locate the test directory (which is typically at /tmp/pytest-of-<username>), serve http from there (I use ```python -m http.server 8001```), connect to localhost:8001 in your browser, and navigate to the latest full_package directory.
The index on the left should contain (and tests confirm) two items, "Python API" and "C++ API". Previously "C++ API" was expanded in the index to include the subitems "Class Hierarchy", "File Hierarchy", and "Reference". That only makes sense if the rosdoc2 output only contains the C++ API. It is intentional that those are now collapsed under a single heading "C++ API" We are adding other items there, now "Python API" …
> Allow ament-cmake-python build types

- rosdoc2/verbs/build/build_context.py
- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/generate_interface_docs.py
- rosdoc2/verbs/build/inspect_package_for_settings.py
- test/packages/full_package/action/Fibonacci.action
- test/test_builder.py
This will show messages, services, and actions (with just their raw text) in packages that already have C++ content. Unfortunately it does not resolve issue #54, that will take additional effort.
In the test cases, full_package has messages, services, and actions that can show how this works.
The majority of real packages that have msg definitions seem to be in msg-only packages, which will still fail. So this PR does not really solve the real-world problem yet, but I will submit a PR to address msg-only packages. It does not really matter to me if this is reviewed and landed first, or if you wait until I resolve the case of message-only packages, it is the same amount of work for me. Your choice.
> Support msgs, services, and actions

- rosdoc2/verbs/build/builders/sphinx_builder.py
Fixes #56 
The html_theme_option 'navigation_depth' has a large impact on the size of the generated output. This patch changes that from infinite (-1) to 4.
Size effects for rmf_utils iron:
depth = 2: 60M
depth = 3: 61M
depth = 4: 112M
depth = -1: 332M
With depth = 4, the C++ API section in the toc shows like:
C++ API
--Full C++ API
----Classes and Structs
------Class LazyExpression
That is, the toc shows the class name, but not any details of the class. You need to click on the name to reach the class page to get that.
I think that is the right amount of detail, plus it is reducing the total file space to 1/3 of the current value.
> Limit navigation_depth to 4, fixes #56

- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/standard_documents.py
- test/packages/full_package/doc/somethingElse.markdown
- test/packages/full_package/quality_declaration.markdown
- test/packages/only_messages/README.md
- test/packages/only_messages/README.rst
- test/packages/only_python/README.txt
- test/test_builder.py
Here we add a section to the home page that lists any of 5 standard documents that are found. It also includes the concept from PR #61 to include the README on the home page. If accepted, this would supersede that PR, but also should give credit here to @ottojo.
I needed tests to pass, so I chose the current tfoote-patch-1 branch to base this on. This PR will need rebasing after a solution is chosen to get tests working again.
> Show standard docs

- rosdoc2/verbs/build/builders/index.rst.jinja
- rosdoc2/verbs/build/builders/sphinx_builder.py
- setup.cfg
This is the first step toward addressing #42. I addressed some of the reasoning there, but let me restate it.
First, the internal templates that are currently used with format_map automatically include various information from the package, such as the package name and version. I want to add additional useful information from package.xml as well, such as the description, urls, and meta-package subpackage list. Currently, if a user decides to customize one of the required files (conf.py, index.rst, or Doxyfile) they should have the same capability as rosdoc2 to automatically include package information.
Second, it is not easy to see what index.rst is supposed to look like with the current method of assembling it from python code. The file index.rst.jinja is (at least to me) much easier to …
> Use Jinja to generate index.rst

- rosdoc2/verbs/build/builders/sphinx_builder.py
- test/packages/only_python/package.xml
> Protect author names from apostrophes with triple quotes

- rosdoc2/verbs/build/builders/index.rst.jinja
- rosdoc2/verbs/build/standard_documents.py
> Rename readme_include.rst to stop name collisions

- rosdoc2/verbs/build/builders/index.rst.jinja
- test/test_builder.py
Note I used package.description rather than package_description. I intend to refactor the template variables to simplify them, in anticipation of documenting them for package authors to use if modifying .jinja files. There is no need to include package attributes that are available directly from the package.
> Add package description to home page

- rosdoc2/verbs/build/builders/index.rst.jinja
- test/test_builder.py
This adds the urls from the package to the home page.
Note these are not included in the index in this version. I could do that, but I think I would need to first generate an rst page containing just these links.
In any case, the home page is getting cluttered now with lots of stuff that is also accessible from the index. I plan to do a revamp of that, hiding many of the items that are in the index from the home page, and simplifying the home page. In that case these URLs would only be on the home page, and not in the index. I think that is the right decision, but it is a matter of opinion.
> Add url links in home page

- rosdoc2/verbs/build/builders/index.rst.jinja
Would it be OK if we gave a slightly more descriptive title? IIUC correctly "Welcome to the documentation for ..." comes from the default package generation for sphinx. We have a little more information, like this is a ROS2 package we are showing. The title should say that. "Welcome to the documentation for ..." is pretty useless verbiage. When I come to the page, particularly if I have lots of tabs opened, it would be good to have more hints of what I am looking at.
We could mark the package title differently if you don't like the <thepackage> style. Italics would also be straightforward.
> Title change to ROS2 Package <thepackage>

- rosdoc2/verbs/build/standard_documents.py
- test/test_builder.py
@tfoote [suggested](https://github.com/ros-infrastructure/rosdoc2/pull/114#issuecomment-2065437667) that package.xml be displayed. Here it is.
> add package.xml to standard documents

- rosdoc2/verbs/build/builders/sphinx_builder.py
Fixes #101 
This just eliminates a warning.
> Use existence of doxygen directory to set C++ API line

- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/inspect_package_for_settings.py
- test/packages/false_python/package.xml
- test/packages/invalid_python_source/package.xml
- test/packages/invalid_python_source/rosdoc2.yaml
- test/packages/src_alt_python/launch/dummy.launch.py
- test/packages/src_alt_python/package.xml
- test/packages/src_alt_python/src/other_name/python_node.py
- test/packages/src_alt_python/src/other_name/subpackage/__init__.py
- test/packages/src_python/package.xml
- test/packages/src_python/src/src_python/python_node.py
- test/packages/too_many_python_packages/package.xml
- test/packages/too_many_python_packages/package1/python_node.py
- test/packages/too_many_python_packages/package2/python_node.py
- test/test_builder.py
Fixes #122 
The changes made here are:
- a failure with the python source directory generates a warning instead of aborting
- if python source directory is not specified, then we search for it using flat layout and source layout. We prefer to find a python package with the same name as the ros package. But if not found by that name, we search for a single python package, and use that.
Tests are included for a variety of cases.
With these changes, the following packages that were not generating output before, now generate a proper output:
```
mavros_extras
message_filters
microstrain_inertial_rqt
nmea_navsat_driver
nodl_python
ntrip_client
python_orocos_kdl_vendor
rmf_traffic_editor_assets
rosbag2_storage_mcap
rosbag2_storage_sqlite3
rqt, plus many related packages rqt_*
system_fingerprint …
```
> Support non-default python layouts

- .gitignore
- stdeb.cfg
In order to make rosdoc2 easier to use locally, I'm preparing to release it via the ros_bootstrap repo into ROS repositories.
While building and running test installs of the package I found a few issues.
* Drop Ubuntu Bionic
* Add Ubuntu Jammy
* Add Ubuntu Noble
* Drop Debian Stretch
* Drop Debian Buster
* Add Debian Bookworm
* Add Debian Trixie
* Drop Ubuntu Focal (exhale and myst-parser are not available on Focal)
> Prepare to release rosdoc2 into the ROS apt repositories.

- stdeb.cfg
Of course, discovered after publishing to apt and PyPI (which is unaffected by this issue).
I thought I'd done a successful dry-run but clearly that was before I snuck the last commit on #128 to include "grapviz". 🤦🏼
> Fix graphviz typo in stdeb.cfg.

- setup.cfg
This was necessary to publish rosdoc2 on PyPI.
> Add long_description_content_type to support publishing on PyPI.

- CHANGELOG.rst
- rosdoc2/__init__.py
Follow-up release to resolve the typo blocking installation of rosdoc2 0.2.0 via apt (#132) and also includes a fix for PyPI publishing (#131).
This change will be fast-forwarded onto main and the first commit will be tagged 0.2.1.
> Prepare 0.2.1

- README.md
> a few cosmetic fixes for README.md.

- rosdoc2/verbs/build/inspect_package_for_settings.py
There are some issues with the yaml syntax of the default config.
I created a default rosdoc2.yaml with `rosdoc2 default_config --package-path src/realtime_tools/`, but the linter complains
```
Flow map in block collection must be sufficiently indented and end with a }YAML
Unexpected flow-map-end token in YAML stream: "}"YAML
```
Increasing the indent fixes this for me.
> Fix flow-map syntax of rosdoc2.yaml

- .github/workflows/test.yml
Welcome back, @tfoote ! 
This just updates our test matrix to include jazzy. I keep iron because IIUC it is running on older ubuntu and python, so might have different issues.
> Use jazzy, iron, and rolling in tests

- rosdoc2/verbs/build/builders/sphinx_builder.py
Fixes #125 
Adds a blank COLCON_IGNORE file to the wrapped directory, to prevent package finders from thinking this is a package to process, as suggested by @damien-robotsix in #125
> Prevent package finders from processing the wrapped directory

- rosdoc2/verbs/open/impl.py
Starting to do general documentation, tried 'open' and found it was lacking and broken.
Here's my update. With this, you can call 'rosdoc2 open' in several ways:
- ```rosdoc2 open``` will open the docs_output directory, which will be a list of directories of package names
- ```rosdoc2 open other_output_directory``` will work with a non-default output_directory (or file)
- ```rosdoc2 open package_name``` will open the documentation for package_name in the default location
> Fix and expand "open" command

- rosdoc2/verbs/build/impl.py
Strange things can happen if there are leftover files in the docs_build directory. I recently came across one: if there is a previous run, then index.rst will already exist, so it will not be updated with index.rst.jinja if anything changes.
I cannot think of any good reason to leave the old docs_builds for the particular package, so this PR erases it at the beginning of the build.
> Remove any existing package doc_build_directory

- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/inspect_package_for_settings.py
- test/packages/default_yaml/rosdoc2.yaml
This is a followup to #138. The original documentation was wrong, doc/ is not a reasonable default for sphinx_sourcedir, as specifying that has the side effect of replacing the standard rosdoc2 output. That 'side effect' is actually the intended main effect of sphinx_sourcedir. We will need a new variable for the common issue that user documentation is in an alternate folder (typically docs/) but we do not want to override the default rosdoc2 output. That is a followup need.
> Use null as default for sphinx_sourcedir

- rosdoc2/verbs/build/builders/sphinx_builder.py
- test/packages/basic_cpp/doc/conf.py
Several packages add unsupported extensions in their conf.py files. Then when sphinx runs, it dies and we get no output.
This adds a check in the wrapping conf.py for the extensions that will be available when rosdoc2 is run in standard environments, and deletes (with a warning) any unsupported extension.
The PR also modifies a test to add all of these (plus one unsupported) to one of the test packages, to make sure that we both succeed with all standard extensions added, and that it does not die with an unsupported extension.
I'm trying to find PRs I can add which do apply cleanly to main (this is one),  but really I need resolution of #139 to make progress.  Most of my other patches cause conflicts which, if I attempt to resolve, will cause my rkent repo to diverge from …
> Removing any unsupported extensions

- rosdoc2/verbs/build/builders/index.rst.jinja
- test/test_builder.py
When I am working with packages, I often find myself going back and forth between rosindex and rosdoc2 representations. rosindex links to rosdoc2, this adds the reverse link from rosdoc2 back to rosindex for the package. It is a simple PR that does not conflict with others.
> Show package index in links

- rosdoc2/verbs/build/builders/sphinx_builder.py
When running rosdoc2 over entire distros (using the scan option), disk usage is quite large. Investigating, the majority of that disk usage is in the .doctrees folder. AFAICT, this folder is only used during generation of the toctrees, and [is not needed for display of the documentation from the html](https://stackoverflow.com/questions/33904042/is-doctrees-folder-required-for-displaying-html-docs-with-sphinx).
This is also an issue on the standard buildfarm, though not as bad. See https://docs.ros.org/en/rolling/p/rclcpp/.doctrees/ for example.
This PR deletes the .doctrees folder after the sphinx documentation generation is complete.
> Remove unneeded .doctrees from sphinx output

- rosdoc2/verbs/build/include_user_docs.py
This is just a fix to an oversight in a previous PR.
> Minor tweak in logger message, 'sphinx_project_directory' should now be 'use_doc_directory'

- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/inspect_package_for_settings.py
- test/packages/ignore_doc/doc/noshow.md
- test/packages/ignore_doc/package.xml
- test/packages/ignore_doc/rosdoc2.yaml
- test/test_builder.py
Some of the larger projects have their own documentation that is built independently of rosdoc2. Rather than trying to duplicate their efforts, we should just allow the projects to add their own link in the 'documentation' area of rosdoc2.
This has the downside that the user leaves the rosdoc2 site, but I still think it is the better option for these projects.
When this PR is built, it should not show any changes since this is a new unused option, but you could see it in the tests. In my full runs, there are a number of sites with this applied (using the previous PR --yaml-extend): pinocchio, fastrtps, beluga, ign_rviz, grbl_ros, fields2cover, depthai-ros. So for example see https://rosdoc2.rosdabbler.com/humble/fields2cover/ and check the Documentation link. (These all also have …
> Allow null user_doc_dir in rosdoc2.yaml to ignore documentation.

- rosdoc2/verbs/build/builders/index.rst.jinja
Fixes a warning during rosdoc2 generation.
> Fix link whitespace to remove warning

- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/package_repo_url.py
- setup.cfg
- stdeb.cfg
- test/packages/rclcpp/package.xml
- test/test_builder.py
Currently, very few package authors actually set the package repository url, which is an official link in package.xml  But in navigating documentation, it is very important to be able to move as smoothly as possible between the rosindex package entry, rosdoc2 entry, and the repo. The repo url is readily available in rosdistro, so this PR looks it up if missing, and adds it.
Note this requires that we know the currently active rosdistro, which is not something that can be discerned directly from the package source. So the PR looks for ROS_DISTRO in the environment, and uses that if found. I'm not sure if the build farm sets that or not for doc jobs, if not that will need to be done to support this.
This also adds a new level of complexity to rosdoc2, that it is now using external …
> Add repository url if missing

- rosdoc2/verbs/build/builders/doxygen_builder.py
This simple change use an absolute path rather than a relative path to locate the Doxyfile.
Generally the absolute vs relative path decisions in rosdoc2 are all over the map, and really need a thorough review.
In the current case, a problem occurred on my local build farm, where the locations of files were set using NFS to locations, with soft links to the actual disk storage locations. The error message in Doxygen reported the actual disk location (that is, with the soft link resolved). That caused a mismatch of the '..' count in the relative link. Perhaps somewhere Doxygen is resolving soft links. Really relative paths do not make sense in calls like this to Doxygen, as we are using relative directories on files that could be on completely separate file systems.
I could live without …
> Use abspath for doxyfile to stop failure

- rosdoc2/verbs/build/inspect_package_for_settings.py
- test/packages/basic_cpp/Doxyfile
- test/packages/false_python/rosdoc2.yaml
Many packages define enable_breathe=false and enable_exhale=false in rosdoc2.yaml, but that is not a valid option there. It IS a valid option in rosdoc2_settings in config.yaml. I suspect there is some cargo culting goin on here (or some incorrect tutorial). What I assume they intend from this is that they do not want to generate C++ API from a Doxygen run.
This PR captures those values, issues a deprecation warning, and then sets never_run_doxygen=true which we assume is the intended effect.
I'm not completely sure this is a good idea, but it is part of my overall effort to make rosdoc2 work as well as possible with the existing package repos. There are other ways to accomplish this (override in yaml extend, or just submit PRs to the affected repos). Opinions welcome.
Here is  a list of …
> Interpret enable_breathe and enable_exhale as never_run_doxygen option.

- rosdoc2/verbs/build/include_user_docs.py
- test/packages/index_excludes_content/doc/somedocs.rst
- test/packages/index_excludes_content/doc/with_index/deeper/a_deep_doc.rst
- test/packages/index_excludes_content/doc/with_index/i_will_not_show/noshow.rst
- test/packages/index_excludes_content/doc/with_index/index.rst
- test/packages/index_excludes_content/doc/with_index/noshow.rst
- test/packages/index_excludes_content/doc/with_index/the_doc.rst
- test/packages/index_excludes_content/doc/without_index/another_doc.rst
- test/packages/index_excludes_content/doc/without_index/subdir1/afile.rst
- test/packages/index_excludes_content/doc/without_index/subdir2/anotherfile.rst
- test/packages/index_excludes_content/package.xml
- test/test_builder.py
Currently, if there is an index.rst in a documentation folder, that does not override the standard directory search for documentation, which results in duplicate entries for documentation, or includes documentation folders that the user expected to be excluded since it was not included in index.rst
The heart of this PR got obscured by a lot of additional cleanup going on.
- renamed sphinx_project_directory to the more accurate rel_user_doc_directory
- reduced some of the levels shown in the documentation tree.  I don't believe in most cases it makes sense to show tree entries for the internals of documentation files.
- creation of a new test file to test the issue.
Really the heart of this is the code:
```python
if 'index.rst' in files:
dirs.clear()
```
You can see the point of this if …
> Don't duplicate doc links if index.rst exists

- rosdoc2/verbs/build/builders/index.rst.jinja
- rosdoc2/verbs/build/builders/sphinx_builder.py
- rosdoc2/verbs/build/include_links.py
Most of the top-level items on the home page also appear in the table of contents, except for links. This adds those links to the TOC.
> Create a links.rst file so links can appear in toc

- rosdoc2/verbs/build/impl.py
- rosdoc2/verbs/scan/impl.py
> Deprecate the --install-directory option

- setup.cfg
There is a private API dependency on sphinx from breathe 4.35, and sphinx 8.2.0 changes that private API in a way that breaks breathe. This issue only appears to manifest in rosdoc2 jobs which process C++.
Example of this failure on the official buildfarm: https://build.ros2.org/view/Jdoc/job/Jdoc__rcl__ubuntu_noble_amd64/10/
> Pin to sphinx < 8.2.0

- rosdoc2/verbs/build/builders/sphinx_builder.py
- test/packages/basic_cpp/doc/_templates/layout.html
- test/test_builder.py
Sphinx projects can include templates that modify how the output appears, for example adding content in a footer. This would typically by specified in a templates directory, relative to where conf.py exists.
The issue we face is that people who specify templates would typically do that in a doc/_templates directory, which is also where a conf.py file would be added (which we rename to __conf.py to avoid certain conflicts, or supply a default if missing).
However, the actual sphinx project that we run, using a conf.py that wraps either a user or a default conf.py, is run in the wrapped_sphinx_directory, not in wrapped_sphinx_directory/doc which is where the templates are. So a templates reference like '_templates' (which we define by default) is looking for the templates in …
> Copy templates to actual sphinx project location

- setup.cfg
This reverts commit 95fa29de85a692ba9c312e70d8c67b912db9b47c.
Breathe has been updated now, and a more robust release procedure implemented in https://github.com/breathe-doc/breathe/pull/1023. I think we want to generally follow newer breathe and sphinx releases rather than pin to a fixed release.
I tested this, using a local venv, by first confirming that I could reproduce the original error by running rosdoc2 on jazzy rcl forcing breathe 4.35.0, then confirming that the error goes away with this PR.
> Revert "Pin to sphinx < 8.2.0 (#174)" as breathe has been updated.

- rosdoc2/verbs/build/builders/sphinx_builder.py
- test/packages/user_index_root/index.rst
- test/packages/user_index_root/package.xml
- test/test_builder.py
Fixes https://github.com/rkent/rosdoc2/issues/4
We currently support an index.rst.jinja in the package directory, but I'd always intended to also support index.rst there. This fixes that.
> Allow user to specify index.rst in package directory

- rosdoc2/verbs/build/builders/sphinx_builder.py
- test/test_builder.py
Since we now have ROS_DISTRO available, this shows the distro in the form '<package_name>: Rolling' following the format in the main ros documentation at https://docs.ros.org/en/rolling/
> Show rosdistro in TOC

- rosdoc2/verbs/build/include_user_docs.py
- test/test_builder.py
Fixes https://github.com/rkent/rosdoc2/issues/41
I'm going through my list of issues, doing easy fixes.
If a user specifies an index.rst file in their doc folder, we should assume that contains everything needed to show the documentation in that folder. Currently, we are treating that like any other documentation file, that is it is included in a list of all of the other document files in that folder. With this change, if the index.rst file exists, only it is shown, and we assume that the user provided a link to whatever else they care about in that file.
> doc/index.rst should override glob of doc/ files

- doc/testing.md
This PR adds documentation for testing.
I want to start landing the documentation for the current version of rosdoc2. I wrote a bunch of  documentation several months ago in a branch https://github.com/rkent/rosdoc2/tree/major-documentation-rewrite. This is one file from that branch.
Is it OK if we land these one at a time (like in this PR), or would you rather bunch them into a big documentation PR?
I've been avoiding reviewing my documentation rewrite myself, while I found this one file fairly easy to test and add. So I would prefer one file at a time.
> Document testing

- README.md
I noticed that the [how-to guide](https://docs.ros.org/en/rolling/How-To-Guides/Documenting-a-ROS-2-Package.html) is not mentioned here. It has some pretty useful information, so I thought it would be good to link to it here.
Note that some of the empty/TODO sub-sections under [Documenting a Package](https://github.com/ros-infrastructure/rosdoc2#documenting-a-package) in the README here are covered by the guide. Not sure if the intention is to also document that here, but for now we can just start with this link.
> Link to the 'Documenting a ROS 2 package' guide

- README.md
- rosdoc2/verbs/build/builders/sphinx_builder.py
- test/packages/full_package/doc/conf.py
Currently, the default user `conf.py` that is generated includes things like the package version, which must then be manually updated to match the version in `package.xml`.  Frequently this is not done, so there is a version mismatch.
Really there is no reason currently why `version =` is recommended in `conf.py` as that is set automatically by the wrapping `conf.py`.  But it is unclear to users (and to me for that matter) what is really required in a user-defined `conf.py`.
So this PR moves all of the required settings for `conf.py` to the wrapping `conf.py`, so that the correct, default user `conf.py` is simply blank. That way, package authors can be encouraged to only include changed or extra variables in their `conf.py`
This PR got expanded with a few cleanups that this change …
> Move all required conf.py variables to generated wrapped conf.py so default user conf.py is blank
